export default {
  name: "homePage",
  title: "Home Page",
  type: "document",
  fields: [
    { name: "eyebrow", title: "Hero eyebrow", type: "string" },
    {
      name: "headline",
      title: "Hero headline",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "intro",
      title: "Hero introduction",
      type: "text",
      rows: 3,
      validation: (Rule) => Rule.required(),
    },
    {
      name: "heroImage",
      title: "Hero image",
      type: "image",
      options: { hotspot: true },
      fields: [
        {
          name: "alt",
          title: "Alternative text",
          type: "string",
          validation: (Rule) => Rule.required(),
        },
      ],
    },
    { name: "primaryCta", title: "Primary action", type: "link" },
    { name: "secondaryCta", title: "Secondary action", type: "link" },
    { name: "aboutKicker", title: "About section label", type: "string" },
    { name: "aboutHeading", title: "About section heading", type: "string" },
    {
      name: "aboutBody",
      title: "About section copy",
      type: "array",
      of: [{ type: "block" }],
    },
    {
      name: "statistics",
      title: "Impact statistics",
      type: "array",
      of: [{ type: "statistic" }],
      validation: (Rule) => Rule.max(4),
    },
    { name: "servicesHeading", title: "Services heading", type: "string" },
    {
      name: "servicesIntro",
      title: "Services introduction",
      type: "text",
      rows: 2,
    },
    { name: "flagshipLabel", title: "Flagship project label", type: "string" },
    { name: "flagshipTitle", title: "Flagship project title", type: "string" },
    {
      name: "flagshipSummary",
      title: "Flagship project summary",
      type: "text",
      rows: 4,
    },
    {
      name: "flagshipImage",
      title: "Flagship project image",
      type: "image",
      options: { hotspot: true },
      fields: [{ name: "alt", title: "Alternative text", type: "string" }],
    },
    { name: "flagshipLink", title: "Flagship project link", type: "link" },
    {
      name: "closingHeading",
      title: "Closing call-to-action heading",
      type: "string",
    },
    {
      name: "closingBody",
      title: "Closing call-to-action copy",
      type: "text",
      rows: 2,
    },
    { name: "closingLink", title: "Closing call-to-action link", type: "link" },
    { name: "seo", title: "SEO", type: "seo" },
  ],
  preview: { prepare: () => ({ title: "Home page" }) },
};
