export default {
  name: "siteSettings",
  title: "Site Settings",
  type: "document",
  fields: [
    {
      name: "organizationName",
      title: "Organization name",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "shortName",
      title: "Short name",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "logo",
      title: "Primary logo",
      type: "image",
      options: { hotspot: true },
      fields: [{ name: "alt", title: "Alternative text", type: "string" }],
    },
    {
      name: "logoMark",
      title: "Compact logo mark",
      type: "image",
      options: { hotspot: true },
    },
    {
      name: "missionLine",
      title: "Footer mission line",
      type: "text",
      rows: 2,
    },
    {
      name: "navigation",
      title: "Primary navigation",
      type: "array",
      of: [{ type: "link" }],
      validation: (Rule) => Rule.max(8),
    },
    { name: "headerCta", title: "Header call to action", type: "link" },
    {
      name: "footerServiceLinks",
      title: "Footer service links",
      type: "array",
      of: [{ type: "link" }],
    },
    { name: "address", title: "Address", type: "text", rows: 3 },
    { name: "email", title: "Email", type: "string" },
    { name: "phone", title: "Phone", type: "string" },
    { name: "linkedinUrl", title: "LinkedIn URL", type: "url" },
    { name: "mapEmbedUrl", title: "Map embed URL", type: "url" },
    { name: "copyrightText", title: "Copyright text", type: "string" },
    { name: "defaultSeo", title: "Default SEO", type: "seo" },
  ],
  preview: { prepare: () => ({ title: "Global site settings" }) },
};
